### ISSUE TITLE
Add option for using prometheus labels instead running selector against API server

### ISSUE THREAD

**Issue by DirectXMan12** [DirectXMan12/k8s-prometheus-adapter#1]
In the case of metrics scraped by the Prometheus Kubernetes service discovery mechanism, it looks like labels on series can get autocreated based on labels from Kubernetes.  This could allow us to bypass querying the main API server, but knowing when these are available might be tricky.

**Comment by antoinne85** [comment]
Based on some trial-and-error I've been doing, it would seem that there's no way to influence the query that's made to Prometheus. Is that correct?

In my case, I have multiple time series against a namespace (e.g. `queue_length{ namespace="some-namespace", queue_name="some-queue" }`) it would be nice to be able to scale resources based on the `queue_length` of an individual `queue_name` instead of the sum for all `queue_name`s.

I'm sure it's crossed your mind, but have you considered something slightly non-standard like parsing the `metricName` from the `HorizontalPodAutoscaler` definition to extract Prometheus-specific labels?

It doesn't necessarily prevent you from having to hit the primary API Server, but it does expose additional functionality. 

For example, if the `metricName` were something like `queue_length{ queue_name="some-queue" }`, anything between the braces would be included as part of the query to Prometheus (in conjunction with whatever other label filters are getting applied as a result of the query to the API Server and the list of resources it returns).

---

To further extend this idea (perhaps too far), if someone were to use this syntax for the `metricName` you can take that as a sign that they're indicating to you _"I expect the values from `target` to be available in Prometheus, in addition to whatever I'm specifying here."

So, for example, if one had specified something like:
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-deployment-hpa
  namespace: my-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: my-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metricName: queue_length{queue_name="some-queue"}
      targetValue: 100
      target:
        apiVersion: v1
        kind: Namespace
        name: my-namespace
```

You could infer that the labels that must be matched are:
* `queue_name="some-queue"`
* `namespace="my-namespace"`

Similarly, if someone provided something like:
```
- type: Object
    object:
      metricName: queue_length{queue_name="some-queue"}
      targetValue: 100
      target:
        apiVersion: v1
        kind: Pod
        name: my-pod-name
```

You may be able to infer that they want to target metrics that match:
* `queue_name="some-queue"`
* `pod=~"my-pod-name.*"`

You've probably already considered something like this before, but I'd be interested in hearing your thoughts.

**Comment by antoinne85** [comment]
Having said all of that, it occurs to me that my particular hurdle would be solved for me if `External` metrics were supported (covered by #65).

The information above, however, is perhaps still relevant to this issue.

I don't have a good understand of the details behind `External` metrics yet, so I'm going to do some more reading. But I might be interested in contributing there or here if it seemed appropriate to you.

**Comment by itskingori** [comment]
@DirectXMan12 is there a way to achieve what to @antoinne85's trying to do in https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/1#issuecomment-400471912? I've already had a look at the new documentation in https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/95 and it doesn't seem possible.

**Comment by DirectXMan12** [comment]
We're working on it -- there's a corresponding label-selector change that needs to be made to the custom metrics API that needs to land first, but that'll allow exactly what you're suggesting.  The PR in kubernetes is https://github.com/kubernetes/kubernetes/pull/64097, and we're hoping to land it for kubernetes 1.12.

**Comment by azalio** [comment]
Any news? It would really nice.

**Comment by L3o-pold** [comment]
Any news? Does https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/247 will allow what @antoinne85 wants?

**Comment by antoinne85** [comment]
@L3o-pold I think everything is in place to allow that.

Though my situation has changed a bit (we've got multiple instances reporting their observation of queue length), I think all the necessary tools are in place to achieve what I needed _at the time_.

For example, I've got:
```
rules:
    external:
    - seriesQuery: '{worker_name=~".+"}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
      name:
        matches: "queue_length"
        as: "queue_length"
      # The query to send to prometheus.
      # When filled it, it'll look something like: avg(queue_length{worker_name="MyWorkerName"})
      # We average it because we have multiple instances reporting it, but they should always be roughly in line with one another.
      metricsQuery: avg(<<.Series>>{<<.LabelMatchers>>})
```

In our case, these metrics aren't associated with a particular K8S resource (hence why they're external metrics and not custom metrics), but the config functionality that's exposed is pretty similar between the two and still allows you to specify a query and inject values into it.

You can take a look at [Metrics Discovery and Presentation Configuration](https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/config.md) for some additional information. It's a _touch_ outdated since External Metrics were added, but I believe it's got enough info to get you going.

**Comment by L3o-pold** [comment]
@antoinne85 Is it possible to do something like this?

```
- type: Object
    object:
      metricName: queue_length{worker_name ="my-worker"}
```

**Comment by antoinne85** [comment]
@L3o-pold It looks like that's part of a K8S HPA object, possibly. To the best of my knowledge, there's no way to directly specify a Prometheus query in those objects. 

As I understand it, the K8S metrics API is designed to be an abstraction under which you can layer whatever metrics backend you want (as long as you have an appropriate adapter). As such, Prometheus queries aren't directly usable. In order to achieve that kind of thing, you'll need to look into Custom Metrics. In essence, you need to:
* Get k8s-prometheus-adapter up and running
* Supply the appropriate config that lets k8s-prometheus-adapter know which metrics from Prometheus you want exposed as custom metrics and how to associate them with which K8S resources
* Configure your HPA to look for the metric/label set that dovetails with the config you supplied the adapter

**Comment by L3o-pold** [comment]
Sorry I am not sure to understand. As I understand it it's not possible to query Prometheus directly, I think we agree on that. 

I am able to fetch custom metrics in HPA from Prometheus but I am only able to fetch `queue_length` metrics not to filter on a particular `worker_name`.

**Comment by antoinne85** [comment]
@L3o-pold Let me ask this question before I start talking about something that might not be relevant to what you're trying to do. Tell me if this description correctly matches your situation:
* You have a pod or a set of pods that are all reading from the same queue.
* You want to autoscale the number of pods based on the length of that queue.
* That queue exists outside of Kubernetes (e.g. Azure Storage Queues, Amazon SQS).

**Comment by L3o-pold** [comment]
@antoinne85 

- I have pods that are reading from the metrics but with different queue.
- Yes, I want to autoscale the number of pods based on the length of that queue.
- The queue **exists** inside of Kubernetes

My metrics look like this `queue_length{queue_name="my-dynamic-queue_name"}`

I need to have pods that querying different `queue_name`. This queue name could be dynamic that why I don't want to create different rules based on this queue name.

**Comment by AaronWGoh** [comment]
@L3o-pold I know this issue is quite old but I'm having the exact same use case w/ dynamic queues, did you end up solving this?

**Comment by L3o-pold** [comment]
@AaronWGoh yeah

```yaml
type: Object
object:
  metric:
    name: http_requests
    selector: {matchLabels: {verb: GET}}
```
