### ISSUE TITLE
Renamed metric doesn't show up

### ISSUE THREAD

**Issue by marcin-kasinski** [DirectXMan12/k8s-prometheus-adapter#113]
Kubernetes v1.11.3
Adapter image: directxman12/k8s-prometheus-adapter-amd64

In prometheus I have metric:
`
MKWEB_exec_time_seconds_max{app="springbootweb",host="MYHOST",instance="10.244.0.19:7070",job="kubernetes-pods",namespace="default",pod="springbootweb-7c5998fdd-ktnw5",pod_template_hash="371554988",region="us-east-1"}
`

I want to rename it in my adapter.

In my config I've added new rule:
```

    - seriesQuery: 'MKWEB_exec_time_seconds_max{namespace!="",pod!=""}'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "pod"}
      name:
        matches: "^(.*)_max"
        as: "${1}_max_x1"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'

```
	  
Problem is that after adding this new rule I can see only original metric pods/MKWEB_exec_time_seconds_max not new one pods/MKWEB_exec_time_seconds_max_x1

Can you tell what is wrong with my configuration ?
