### ISSUE TITLE
Create Rule for Traefik

### ISSUE THREAD

**Issue by SoulKyu** [DirectXMan12/k8s-prometheus-adapter#121]
Hello,
I would like to create an HPA with a metrics from traefik : 
```yaml
traefik_backend_requests_total{backend="traefik.guilan.fr",code="200",method="GET",protocol="http"}
```
which return me this in the prometheus/graph url : 
```yaml
{backend="traefik.guilan.fr",code="200",instance="traefik-web-ui.traefik.svc.cluster.local:80",job="traefik",method="GET",protocol="http"}
```

but in fact i don't know how to create the rule ..
i've create this but it doesn't work : 
```yaml
    - seriesQuery: 'traefik_backend_requests_total{backend="traefik.guilan.fr",code="200",method="GET",protocol="http"}'
      resources:
        overrides:
          backend: {resource: "namespace"}
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'rate(traefik_backend_requests_total{backend="traefik.guilan.fr",code="200",method="GET",protocol="http"}[2m]) by'
```

I think the real problem is that i don't understand well how to create a rule .. :/

Could you please help me with this ?
BR,
