### ISSUE TITLE
403 in the readiness probe on AKS

### ISSUE THREAD

**Issue by cradle77** [DirectXMan12/k8s-prometheus-adapter#151]
Dear all,

I'm trying to install the Prometheus Adapter in an RBAC enabled AKS Kubernetes cluster:

```
helm install stable/prometheus-adapter --name prometheus-adaptor -f ./autoscale-demo/prometheus-adapter/values.yaml
```

Nothing special on the values.yaml file:
```
# Url to access prometheus
prometheus:
  url: http://prometheus-prometheus-0.default.svc.cluster.local
  port: 9090

metricsRelistInterval: 30s
logLevel: 6
rules:
  default: false
  custom:
  - seriesQuery: 'request_durations_histogram_secs_count{namespace!="", pod!=""}'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod: {resource: "pod"}
    name:
     as: "requests_per_second"
    metricsQuery: 'round(avg(irate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>))'
```
(I'm just following this walkthrough for POD autoscale: https://azure.microsoft.com/en-gb/resources/samples/virtual-node-autoscale/ )

However, the pods never becomes ready, as the readiness and liveness probe calls fail with a 403.

```
bash-4.4# kubectl describe pod prometheus-adaptor-prometheus-adapter-5cddf7cc64-xphk6
Name:               prometheus-adaptor-prometheus-adapter-5cddf7cc64-xphk6
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-nodepool1-17033719-0/10.240.0.4
Start Time:         Mon, 17 Dec 2018 09:40:04 +0000
Labels:             app=prometheus-adapter
                    chart=prometheus-adapter-v0.2.1
                    heritage=Tiller
                    pod-template-hash=1788937720
                    release=prometheus-adaptor
Annotations:        checksum/config: ee31aefa97b81c3c6f2332640107d252093b9c0282d87cefedf445bbd9d80a37
Status:             Running
IP:                 10.240.0.21
Controlled By:      ReplicaSet/prometheus-adaptor-prometheus-adapter-5cddf7cc64
Containers:
  prometheus-adapter:
    Container ID:  docker://76267031daeb5ef6457febb3c75d6ab952de98c3eaa447db2d7bdc6f55527286
    Image:         directxman12/k8s-prometheus-adapter-amd64:v0.4.0
    Image ID:      docker-pullable://directxman12/k8s-prometheus-adapter-amd64@sha256:a413730093da3a7a7048240ca88f68595cfd141eb36d9be400b10f0081df0e3d
    Port:          6443/TCP
    Host Port:     0/TCP
    Args:
      /adapter
      --secure-port=6443
      --cert-dir=/tmp/cert
      --logtostderr=true
      --prometheus-url=http://prometheus-prometheus-0.default.svc.cluster.local:9090
      --metrics-relist-interval=30s
      --v=6
      --config=/etc/adapter/config.yaml
    State:          Running
      Started:      Mon, 17 Dec 2018 09:42:01 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 17 Dec 2018 09:41:01 +0000
      Finished:     Mon, 17 Dec 2018 09:42:00 +0000
    Ready:          False
    Restart Count:  2
    Liveness:       http-get https://:https/healthz delay=30s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get https://:https/healthz delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  desakswe4-desakswe4-cbbd3e-6c3dc1d9.hcp.westeurope.azmk8s.io
      KUBERNETES_PORT:               tcp://desakswe4-desakswe4-cbbd3e-6c3dc1d9.hcp.westeurope.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://desakswe4-desakswe4-cbbd3e-6c3dc1d9.hcp.westeurope.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       desakswe4-desakswe4-cbbd3e-6c3dc1d9.hcp.westeurope.azmk8s.io
    Mounts:
      /etc/adapter/ from config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-adaptor-prometheus-adapter-token-2d69w (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-adaptor-prometheus-adapter
    Optional:  false
  prometheus-adaptor-prometheus-adapter-token-2d69w:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-adaptor-prometheus-adapter-token-2d69w
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                               Message
  ----     ------     ----                 ----                               -------
  Normal   Scheduled  2m39s                default-scheduler                  Successfully assigned default/prometheus-adaptor-prometheus-adapter-5cddf7cc64-xphk6 to aks-nodepool1-17033719-0
  Normal   Pulled     43s (x3 over 2m38s)  kubelet, aks-nodepool1-17033719-0  Container image "directxman12/k8s-prometheus-adapter-amd64:v0.4.0" already present on machine
  Normal   Killing    43s (x2 over 103s)   kubelet, aks-nodepool1-17033719-0  Killing container with id docker://prometheus-adapter:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Created    42s (x3 over 2m38s)  kubelet, aks-nodepool1-17033719-0  Created container
  Normal   Started    42s (x3 over 2m37s)  kubelet, aks-nodepool1-17033719-0  Started container
  Warning  Unhealthy  4s (x7 over 2m4s)    kubelet, aks-nodepool1-17033719-0  Readiness probe failed: HTTP probe failed with statuscode: 403
  Warning  Unhealthy  3s (x7 over 2m3s)    kubelet, aks-nodepool1-17033719-0  Liveness probe failed: HTTP probe failed with statuscode: 403
```

Any idea on what might be going on?

**Comment by DirectXMan12** [comment]
something's probably wrong with the rbac or auth presented by the readiness probe.  Note that we don't officially support them helm adapter (it's a community effort, IIRC), but if I had to guess, something's wrong with however the probe is configured.  Can you check the actual message from the probe, or try reproducing the probe yourself?

**Comment by cradle77** [comment]
Hello @DirectXMan12 , first and foremost thanks for getting back to me

I've checked the kubelet logs but it really doesn't say much more than that:
```
-4s6wx_default(b062b8c8-0514-11e9-ac59-8ef8c1dc0bcc):prometheus-adapter" failed (failure): HTTP probe failed with statuscode: 403
4s6wx_default(b062b8c8-0514-11e9-ac59-8ef8c1dc0bcc):prometheus-adapter" failed (failure): HTTP probe failed with statuscode: 403
```

This is what I see in the *pod* logs
```
I1221 13:34:14.016071       1 authorization.go:73] Forbidden: "/healthz", Reason: ""
I1221 13:34:14.016222       1 wrap.go:42] GET /healthz: (10.122888ms) 403 [[kube-probe/1.11] 10.240.0.4:44526]
```

This is the manifest of the deployment, in regards to probes:
```
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: https
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: "/healthz"
            port: https
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
```
Any specific roles I should check for, in the service account?

Thanks in advance for your help
