### ISSUE TITLE
Missing info regarding complex label concatenation

### ISSUE THREAD

**Issue by thejasbabu** [DirectXMan12/k8s-prometheus-adapter#152]
I am currently using the k8s-prometheus-adapter along with yet-another-cloudwatch exporter to autoscale my pods based on the `aws_elb_requestcount_sum` metrics of the service. 

Read the documentation about defining the rules for k8s-prometheus-adapter, but the aws_elb_requestcount_sum metric contains a field name that needs to be joined with aws_elb_info metrics and then fetch the metrics based on tag_kubernetes_io_service_name tag which is namespace/svc name.

How do I form my metricsQuery, can I do some kind of templating like below.  

```
  - seriesQuery: 'aws_elb_requestcount_sum{name!=""}'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        service: {resource: "service"}
    name:
      matches: "aws_elb_requestcount_sum"
      as: "aws_elb_requestcount_sum"
    metricsQuery: sum(aws_elb_requestcount_sum and on (name) aws_elb_info{tag_kubernetes_io_service_name="__namespace__/__service__"})

```

**Comment by thejasbabu** [comment]
@DirectXMan12 Sorry, but can you redirect me to docs which tells how to form the rules required for the `k8s-prometheus-adapter`. Also there seems to be a little confusion from the default `http_request` metrics as shown by @luxas in his example.

1. How is the `http_requests` in HPA getting converted to read from `http_requests_totals` in prometheus? I checked the default set of rules, they don't seem to have this rule. Please correct me if I'm wrong.

2. How are dimensions specified of the metrics. If there is a metric which is emitted by ELB (kubernetes service), why is that while I query for list of custom metrics that I see those metrics available at pod, namespace and job dimensions?

**Comment by thejasbabu** [comment]
Adding my HPA.

```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: details
  namespace: book-info
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: details-v1
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: container_memory_working_set_bytes
      targetAverageValue: 1
```
