### ISSUE TITLE
Issues creating a Prometheus Adapter Rule

### ISSUE THREAD

**Issue by sepulworld** [DirectXMan12/k8s-prometheus-adapter#153]
Here is a query that is working well in Prometheus. What would a corresponding Prometheus Adapter Rule look like to get this exposed in the custom-metrics API for HPA to use? 

```
rate(istio_request_duration_seconds_bucket{destination_service="data-sources-master.app.svc.cluster.local",destination_service_name="data-sources-master",destination_service_namespace="app",job="istio-mesh",reporter="destination",request_protocol="http",response_code="200"}[1m])
```

I've taken many different approaches based upon documentation but can't get a working solution. Any help would be greatly appreciated 👍

**Comment by sepulworld** [comment]
Ok, I think I dialed it in.

```
rules:
  custom:
  - seriesQuery: '{__name__=~"^istio_request_.*"}'
    resources:
      overrides:
        destination_service_namespace:
          resource: namespace
        destination_service_name:
          resource: services
    name:
      matches: ^istio_request_(.*)$
      as: "istio_request_$1"
    metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
```

I had to map the service and namespace labels that were metric label specific to the resource endpoints. I believe this is the way to role here. Correct me if I am wrong.

```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/app/services/data-sources-master-bots/istio_request_duration_seconds_count"

{"kind":"MetricValueList","apiVersion":"custom.metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/custom.metrics.k8s.io/v1beta1/namespaces/app/services/data-sources-master-bots/istio_request_duration_seconds_count"},"items":[{"describedObject":{"kind":"Service","namespace":"app","name":"data-sources-master-bots","apiVersion":"/v1"},"metricName":"istio_request_duration_seconds_count","timestamp":"2018-12-19T19:42:33Z","value":"145m"}]}
```

I still need to confirm HPA will work next... but looking good so far.

**Comment by sepulworld** [comment]
Ok, HPA is working well.

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: app-master
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: app-master
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Object
    object:
      metricName: istio_request_duration_seconds_count
      target:
        kind: Service
        name: app-master
        apiVersion: /v1
      targetValue: 300m
```

To view
```
kubectl get hpa.v2beta1.autoscaling app-master -n app
```

To edit
```
kubectl edit hpa.v2beta1.autoscaling app-master -n app
```

Closing out. I think the key thing I was missing was the proper associations with K8s resources in the initial prom adapter rule.
