### ISSUE TITLE
[question] How to disable "Failed to list nodes" logs

### ISSUE THREAD

**Issue by carlioth** [DirectXMan12/k8s-prometheus-adapter#156]
I have the k8s-prometheus-adapter working as expected. But I do keep getting some logs once every second that I'd like to disable. 

I've tried to change the --v to 1 and 2. That got rid of the info logs, but I still got the Error logs. 
I also tried to change the --stderrthreshold to 3 to only get FATAL logs, but the Error logs still keep comming. 

Screenshot of the logs and my Deployment details below: 

<img width="1307" alt="outputlogs" src="https://user-images.githubusercontent.com/908670/50695929-603ae500-103e-11e9-90df-8c15c98a8da6.png">

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-metrics-apiserver
  name: custom-metrics-apiserver
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: custom-metrics-apiserver
      name: custom-metrics-apiserver
    spec:
      serviceAccountName: custom-metrics-apiserver
      containers:
      - name: custom-metrics-apiserver
        resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "128Mi"
        image: quay.io/coreos/k8s-prometheus-adapter-amd64:v0.4.1
        args:
        - --secure-port=6443
        - --logtostderr=true
        - --prometheus-url=http://prometheus.monitoring.svc:9090/
        - --metrics-relist-interval=30s
        - --v=2
        - --config=/etc/adapter/config.yaml
        ports:
        - containerPort: 6443
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/adapter/
          name: config
          readOnly: true
        - mountPath: /tmp
          name: tmp-vol
      volumes:
      - name: config
        configMap:
          name: adapter-config
      - name: tmp-vol
        emptyDir: {}

```
