### ISSUE TITLE
Prometheus Rule empty in adaptor

### ISSUE THREAD

**Issue by s3than** [DirectXMan12/k8s-prometheus-adapter#166]
I've configured a rule that returns a specific metric based on backend requests

The adaptor is making the following call to prometheus

http://prometheus-k8s.monitoring.svc:9090/api/v1/series?match%5B%5D=pdf_backend_requests%7Bnamespace%21%3D%22%22%2Cservice%21%3D%22%22%7D&start=1550548004.45

Which when run in the browser returns the details below

```
{"status":"success","data":[{"__name__":"pdf_backend_requests","namespace":"ca","service":"traefik"}]}
```

However when the adaptor does the request it returns from the logs 

```
{"status":"success","data":[]}
```

The rule in the adaptor
```
    - seriesQuery: 'pdf_backend_requests{namespace!="",service!=""}'
      resources:
        template: <<.Resource>>
      name:
        matches: ^pdf_backend_requests$
        as: ""
      metricsQuery: <<.Series>>{<<.LabelMatchers>>}
```

The record in prometheus

```
record: pdf_backend_requests 
expr: sum
  by(service) (rate(traefik_backend_requests_total{backend=~".*pdfextractor.*"}[1m])) 
labels: 
  namespace: ca 
  service: traefik
```

All other metrics appear as expected
