### ISSUE TITLE
Create a seriesQuery with histogram_quantile

### ISSUE THREAD

**Issue by cmendesce** [DirectXMan12/k8s-prometheus-adapter#174]
Dear all,

I'm trying to create a seriesQuery in that the metricsQuery is a histogram_quantile to use in HPA scaling. I want to scale based on 95th.

Here my seriesQuery. 

```
- seriesQuery: '{__name__="caddy_http_request_duration_seconds_bucket",namespace!="",pod!=""}'
      resources:
        overrides:
          pod: 
            resource: pod
          namespace:
            resource: namespace
      name:
        matches: "^(.*)_bucket"
        as: "${1}_95p"
      metricsQuery: 'histogram_quantile(0.95, sum(irate(caddy_http_request_duration_seconds_bucket{<<.LabelMatchers>>}[1m])) by (le))'
```

The query appears in the custom-metrics-api, but with no values in items array. I suspect the cause is the function `histogram_quantile` doesn't return labels, only values, so that custom-metric can't binding with a pod or other resource. 

If it's true, how can I use histogram_quantile in a seriesQuery?

Thanks in advance!
