### ISSUE TITLE
HPA filtering with label

### ISSUE THREAD

**Issue by jondeandres** [DirectXMan12/k8s-prometheus-adapter#177]
We have few metrics scrapped with Prometheus like these:

```
tube_current_jobs_ready{exported_instance="queue01:11300",instance="10.4.1.100:8080",job="beanstalkd",k8s_namespace="dev",k8s_pod_name="dumb-metrics-68bb8f6dd6-5m6sv",k8s_service="beanstalkd",tube="rql"}	50000
tube_current_jobs_ready{exported_instance="queue01:11300",instance="10.4.1.100:8080",job="beanstalkd",k8s_namespace="dev",k8s_pod_name="dumb-metrics-68bb8f6dd6-5m6sv",k8s_service="beanstalkd",tube="trigger"}	10000
```

So we have a `tube_current_jobs_ready` metric per `tube` label, where `tube` is `trigger` or `rql`. I can define some rules in prometheus-adapter to serve those metrics through the custom metrics API:

```
- seriesQuery: 'tube_current_jobs_ready'
      seriesFilters: []
      resources:
        overrides:
          k8s_namespace: {resource: 'namespaces'}
          k8s_service: {resource: 'services'}
      name:
        matches: tube_current_jobs_ready
        as: ""
      metricsQuery: <<.Series>>{<<.LabelMatchers>>}
```
The list of metrics:

```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/"  |jq .                        (gke_rollbar-dev_us-central1-a_jon/default)
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "namespaces/tube_current_jobs_ready",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "services/tube_current_jobs_ready",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```

And I can take the metric:

```
➜  ~ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/dev/services/beanstalkd/tube_current_jobs_ready" | jq .                     (gke_rollbar-dev_us-central1-a_jon/default)
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/dev/services/beanstalkd/tube_current_jobs_ready"                                                                              
  },
  "items": [
    {
      "describedObject": {
        "kind": "Service",
        "namespace": "dev",
        "name": "beanstalkd",
        "apiVersion": "/v1"
      },
      "metricName": "tube_current_jobs_ready",
      "timestamp": "2019-03-15T14:43:00Z",
      "value": "10k"
    }
  ]
}
```

The value is the sum of the two metrics I have for the different values of the label `queue`. The question is, is possible filtering the metric by an extra label when getting it? So I would be able to take the metric for each value of `queue`.

If not, is there anyway to build the metric name given the `queue` value?

**Comment by s-urbaniak** [comment]
@jondeandres You could either a) create separate recording rules for the different labels or create two different series queries, one filtering for `tube="rql"`, the other filtering for `tube="trigger"`. Just an unverifed example:

```
- seriesQuery: 'tube_current_jobs_ready{tube="rql"}'
      seriesFilters: []
      resources:
        overrides:
          k8s_namespace: {resource: 'namespaces'}
          k8s_service: {resource: 'services'}
      name:
        matches: tube_current_jobs_ready
        as: tube_current_jobs_ready_rql
      metricsQuery: <<.Series>>{tube="rql",<<.LabelMatchers>>}
```

The `trigger` example would be equivalent.
