### ISSUE TITLE
Node resource can not be accessed correctly

### ISSUE THREAD

**Issue by xjas** [DirectXMan12/k8s-prometheus-adapter#178]
**What happened:**

Using `kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/" | jq . | less`, I get a unexpected response, as follows:
```
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "nodes/http_requests",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "namespaces/http_requests",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "pods/http_requests",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```

And also, using `kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/node/*/http_requests" | jq . | less`, 
I get a unexpected response:
`Error from server (NotFound): the server could not find the metric http_requests for node`

**What you expected to happen:**

In my opinion, the resouce node should in the same hierarchy with resouce namespace, because in kubernetes they are non-namespaced apparently. And I have request the metric `http_requests` of the resource `namespace`, and it response as expected.

Personally, I think  the fileld `namespaced` should be false for resource `nodes/http_requests`, and the request `kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/node/*/http_requests" should return the correct metric info.

**How to reproduce it (as minimally and precisely as possible):**
Just use the config rules I pasted and make requests: `kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/" | jq . | less` and  `kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/node/*/http_requests" | jq . | less`.

**Environment:**
- Kubernetes v1.9.6
- Adapter image: directxman12/k8s-prometheus-adapter-amd64:v0.4.0
- Adapter image: directxman12/k8s-prometheus-adapter-amd64:v0.4.1(build it with cmd `make build-local-image`)
- My config rule is as follows:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: custom-metrics
data:
  config.yaml: |
    rules:
    - seriesQuery: '{namespace!="",endpoint="http-metrics"}'
      seriesFilters:
      - is: .*ttp_requests_total
      resources:
        overrides:
          namespace:
            resource: namespace
          node:
            resource: node
          pod:
            resource: pod
      name:
        matches: ^(.*)_total$
        as: ""
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
```
