### ISSUE TITLE
Document Prometheus labels needed

### ISSUE THREAD

**Issue by pingles** [DirectXMan12/k8s-prometheus-adapter#18]
The adapter makes some assumptions about the Prometheus labels attached to metrics. We had problems originally when it couldn't find a Pod metric because it was missing the `pod` label.

To scrape Pod metrics correctly we ended up with something like this in our Prometheus config:

```
scrape_configs:
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: pod
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace
```

I've not looked into collecting metrics for other types of object (Ingress, Service etc.) but I'm guessing they probably also depend on certain labels. It'd be great to have a reference that says which labels must be set in Prometheus for it to succeed.

Thanks!
