### ISSUE TITLE
Allow fetching non-namespaced metrics

### ISSUE THREAD

**Issue by DirectXMan12** [DirectXMan12/k8s-prometheus-adapter#21]
We currently don't support metrics on non-namespaced resources (except namespaces themselves).  We need to figure out a quick way to discover all Kubernetes-related non-namespaced metrics (since we can't just look for the namespace label when listing available metrics like we do for namespaced resources).

**Comment by MJGD** [comment]
I think this is the issue I'm running into.

I set up my rules thusly:

```    rules:
    - seriesQuery: '{__name__=~"^rabbitmq_queue.*"}'
      seriesFilters: []
      resources:
        template: <<.Resource>>
      name:
        matches: ""
        as: ""
      metricsQuery: rate(<<.Series>>[1m])
```

and see 

```
mjgd@dev:~/src/k8s-prometheus-adapter$ kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/ | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "jobs.batch/rabbitmq_queue_disk_writes",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "jobs.batch/rabbitmq_queue_messages_published_total",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {

...
```
and I've not been able to write an HPA config which scales off these metrics.

Is there some way I can do this now? changing the Prometheus config maybe? and is there any documentation on how to do it or can someone point me in the right direction please.

If this isn't possible now, then does anyone have an idea when it will be, and can I do anything to help?

**Comment by DirectXMan12** [comment]
This issue became obsolete with the merging of the advanced config branch, so it should be possible now.

Your problem is that you don't have any resources associated with your metric (except for the erroneous `job` label from Prometheus).  What labels do you metrics have?

**Comment by MJGD** [comment]
Ah ok, that was my other thought that I was getting the config wrong, which seems to be the case.

I've tried again but I fear I'm missing something.

I want to scale on the `rabbitmq_queue_messages_ready` metric so I've changed my seriesQuery to look like:
`- seriesQuery: '{__name__="rabbitmq_queue_messages_ready"}'`

When I run this query in prometheus, it produces a selection of lines that look like 

```
rabbitmq_queue_messages_ready{app="rabbitmq",component="rabbitmq-stats",durable="true",instance="10.24.73.11:9090",job="kubernetes-pods",kubernetes_namespace="default",kubernetes_pod_name="rabbitmqstats-579dc8544-vqwrx",pod_template_hash="135874100",policy="ha-two",queue="worker.foo",vhost="/"}
```
So clearly I need to have the right resources section but I'm not sure what I need here.

**Comment by DirectXMan12** [comment]
yeah, unfortunately, there's not a good way to split fields right now.  It's a problem that's come up before, but I'm not quite certain how I want to solve it without making the config language even more complicated.

**Comment by MJGD** [comment]
So for now I need to name the queues the same as the worker deployments or add another label in prometheus which has the same name as the worker deployment?

I shall give that a try and report back.

**Comment by DirectXMan12** [comment]
> add another label in prometheus which has the same name as the worker deployment?

Yes, basically, you have to have *some* label that represents namespace by itself, as well as *some* label that represents deployment by itself.

**Comment by MJGD** [comment]
Today I tried a few more things but still no success:

My config-map for the adapter now looks like

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
    - seriesQuery: 'rabbitmq_queue_messages_ready{queue="foo"}'
      seriesFilters: []
      resources:
        overrides:
          queue: {resource: "deployment"}
      name:
        as: "analytics-comms-trust"
      metricsQuery: 'rate(rabbitmq_queue_messages_ready{queue="foo"}[1m])'
```
and thus when I `kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 | jq` I get 

```
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "deployments.extensions/analytics-comms-trust",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```
Which looks good, but when I try this hpa config 
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: foo
    component: analytics
  name: foo
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: foo
  metrics:
  - type: Object
    object:
      metricName: foo
      target:
        kind: Deployment
        name: foo
```
I see `unknown/10` in the TARGETS column of `kubectl get hpa` 

I've tried manually finding the endpoint in the api by commands such as `kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/deployments.extensions/foo/` but all my attempts result in  `Error from server (NotFound): the server could not find the requested resource` so I clearly don't understand what I'm trying to do there.

Any suggestions?
