### ISSUE TITLE
Multiple custom metrics does not work

### ISSUE THREAD

**Issue by czhao** [DirectXMan12/k8s-prometheus-adapter#217]
The custom metric configuration works for me but when I attempt to use more than 1 custom metrics, like shown below, only the second metric show in the API list and the first one is missing in action.  Any suggestion?
```
rules:
  default: false
  custom:
    - seriesQuery: 'envoy_cluster_upstream_rq_active{envoy_cluster_name="cluster_feature_rpc_dev_50051"}'
      resources: {template: "<<.Resource>>"}
      name:
        as: "active_requests_per_min_dev"
      metricsQuery: 'sum(max_over_time(envoy_cluster_upstream_rq_active{envoy_cluster_name="cluster_feature_rpc_dev_50051"}[1m])) by (<<.GroupBy>>)'
    - seriesQuery: 'envoy_cluster_upstream_rq_active{envoy_cluster_name="cluster_feature_rpc_50051"}'
      resources: {template: "<<.Resource>>"}
      name:
        matches: "^(.*)_rq_active"
        as: "${1}_rq_active_per_min_prod"
      metricsQuery: 'sum(max_over_time(envoy_cluster_upstream_rq_active{envoy_cluster_name="cluster_feature_rpc_50051"}[1m])) by (<<.GroupBy>>)'
```
The result is
```
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 | jq . 
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "namespaces/envoy_cluster_upstream_rq_active_per_min_prod",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "pods/envoy_cluster_upstream_rq_active_per_min_prod",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "services/envoy_cluster_upstream_rq_active_per_min_prod",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "jobs.batch/envoy_cluster_upstream_rq_active_per_min_prod",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```
