### ISSUE TITLE
External metrics filtering

### ISSUE THREAD

**Issue by marcoreni** [DirectXMan12/k8s-prometheus-adapter#236]
Hi all,

I'm trying to setup an external metric to retrieve a lag value from Kafka.
Here is my (external) rule configuration:
```yaml
    - seriesQuery: '{__name__=~"^kafka_consumergroup_.*"}'
      resources:
        template: <<.Resource>>
      metricsQuery: "<<.Series>>{<<.LabelMatchers>>}"
```

This correctly expose some different metrics. I'm able to filter for a single metric using `kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/*/kafka_consumergroup_lag_sum`
Here is the response:
```json
{
    "kind": "ExternalMetricValueList",
    "apiVersion": "external.metrics.k8s.io/v1beta1",
    "metadata": {
        "selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/%2A/kafka_consumergroup_lag_sum"
    },
    "items": [
        {
            "metricName": "kafka_consumergroup_lag_sum",
            "metricLabels": {
                "__name__": "kafka_consumergroup_lag_sum",
                "consumergroup": "consumer-group-1",
                "endpoint": "kafka-exporter",
                "instance": "xx.xx.xx.xx",
                "job": "kafka-exporter",
                "namespace": "my-namespace",
                "pod": "xxx-kafka-exporter-yyy",
                "service": "kafka-exporter",
                "topic": "topic-1"
            },
            "timestamp": "2019-09-05T14:28:05Z",
            "value": "0"
        },
        {
            "metricName": "kafka_consumergroup_lag_sum",
            "metricLabels": {
                 "__name__": "kafka_consumergroup_lag_sum",
                "consumergroup": "consumer-group-2",
                "endpoint": "kafka-exporter",
                "instance": "xx.xx.xx.xx",
                "job": "kafka-exporter",
                "namespace": "my-namespace",
                "pod": "xxx-kafka-exporter-yyy",
                "service": "kafka-exporter",
                "topic": "topic-2"
            },
            "timestamp": "2019-09-05T14:28:05Z",
            "value": "0"
        }
    ]
}
```

I assumed to be able to filter for one specific item using `selector`, but `kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/*/kafka_consumergroup_lag_sum?selector=consumergroup%3Dconsumer-group-1"` yields the same unfiltered result as before.

My target goal is to declare an HPA using a selector, to get a specific metric for each specific HPA without needing to declare multiple rules inside prometheus-adapter (ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-metrics-not-related-to-kubernetes-objects )

Is this doable?

**Comment by marcoreni** [comment]
NVM.

For further reference, after some additional investigation it seems that:
1- K8s documentation is probably outdated, HPA must be defined using the standard selector spec:
```yaml
[...]
  metrics:
    - type: External
      external:
        metric:
          name: kafka_consumergroup_lag_sum
          selector: 
            matchLabels:
              consumergroup: consumer-group-1
[...]
```

2- the raw query performed towards prometheus-adapter (seen in logs) is:
`/apis/external.metrics.k8s.io/v1beta1/namespaces/*/kafka_consumergroup_lag_sum?labelSelector=consumergroup%3Dconsumer-group-1`
and this returns the expected, filtered result.
