### ISSUE TITLE
Metric labels not showing up with metrics

### ISSUE THREAD

**Issue by chamo92** [DirectXMan12/k8s-prometheus-adapter#243]
I have kafka metrics that are being exported to prometheus through the [kafka-lag-exporter](https://github.com/lightbend/kafka-lag-exporter), When I query prometheus from the command line, I get the following: 
 ```
$ curl 'http://my_prometheus:9090/api/v1/query?query=kafka_consumergroup_group_max_lag' | jq
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "kafka_consumergroup_group_max_lag",
          "cluster_name": "my-cluster",
          "endpoint": "http",
          "group": "consumer-3",
          "instance": "10.1.1.37:8000",
          "job": "kafka-lag-exporter-service",
          "namespace": "monitoring",
          "pod": "kafka-lag-exporter-64948cc8-vjz8j",
          "service": "kafka-lag-exporter-service"
        },
        "value": [
          1570329670.824,
          "NaN"
        ]
      },
      {
        "metric": {
          "__name__": "kafka_consumergroup_group_max_lag",
          "cluster_name": "my-cluster",
          "endpoint": "http",
          "group": "consumer-2",
          "instance": "10.1.1.37:8000",
          "job": "kafka-lag-exporter-service",
          "namespace": "monitoring",
          "pod": "kafka-lag-exporter-64948cc8-vjz8j",
          "service": "kafka-lag-exporter-service"
        },
        "value": [
          1570329670.824,
          "0"
        ]
      },
      {
        "metric": {
          "__name__": "kafka_consumergroup_group_max_lag",
          "cluster_name": "my-cluster",
          "endpoint": "http",
          "group": "consumer",
          "instance": "10.1.1.37:8000",
          "job": "kafka-lag-exporter-service",
          "namespace": "monitoring",
          "pod": "kafka-lag-exporter-64948cc8-vjz8j",
          "service": "kafka-lag-exporter-service"
        },
        "value": [
          1570329670.824,
          "2"
        ]
      }
    ]
  }
}

```

Querying the custom metrics:

```
$ kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/services/*/kafka_consumergroup_group_offset | jq
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/services/%2A/kafka_consumergroup_group_offset"
  },
  "items": [
    {
      "describedObject": {
        "kind": "Service",
        "namespace": "monitoring",
        "name": "kafka-lag-exporter-service",
        "apiVersion": "/v1"
      },
      "metricName": "kafka_consumergroup_group_offset",
      "timestamp": "2019-10-06T02:45:37Z",
      "value": "28737"
    }
  ]
}

```
Here are the rules that I have in my prometheus adapter config file:
```
rules:
  default: false
  custom:
    - seriesQuery: '{__name__="kafka_consumergroup_group_offset",namespace!="",service!="",pod!="",group!=""}'
      seriesFilters: []
      resources:
        template: <<.Resource>>
      name:
        matches: ^kafka_consumergroup_group_offset$
        as: ""
      metricsQuery: '<<.Series>>{<<.LabelMatchers>>}'
```

Is there a way to get the labels to show up in the custom metrics? I saw it [here](https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/236), but that was with external metrics. The end goal is to filter based on the "group" label with an HPA to scale the appropriate consumer group.
