### ISSUE TITLE
Unexpectedly High Results

### ISSUE THREAD

**Issue by dokipen** [DirectXMan12/k8s-prometheus-adapter#279]
Here's my rule:
```yaml
  - seriesQuery: 'istio_requests_total{reporter="destination",namespace!="",pod!=""}'
    resources:
      overrides:
        namespace: { resource: "namespace" }
        pod: { resource: "pod" }
    name:
      matches: "istio_requests_total"
      as: "istio_requests_rate"
    metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
```
I can see the prometheus-adapter getting the request `/apis/custom.metrics.k8s.io/v1beta1/namespaces/rito-production/pods/%2A/istio_requests_rate?labelSelector=app.kubernetes.io%2Fname%3Dapp%2Capp.kubernetes.io%2Fversion%3Dversion` which returns the correct number of results, 1 per pod, but the numbers seem about 6x higher than expected.

If I run `sum by(pod) (rate(istio_requests_total{reporter="destination",pod="podname"}[1m]))` I get the expected result. Any idea what I'm doing wrong? Is there a way to debug `.LabelMatchers` and `.GroupBy`? What's being inserted there?
