### ISSUE TITLE
items[] is empty, on specific queries

### ISSUE THREAD

**Issue by shalev123d** [DirectXMan12/k8s-prometheus-adapter#296]
Hello!

I'm trying to query sum(rate(http_requests_total[2m])), with the configuration:

```
    - seriesQuery: 'http_requests_total'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(http_requests_total[2m]))'
```

 which should return:
![image](https://user-images.githubusercontent.com/36129614/84045748-da009c00-a9b1-11ea-82f4-7786ca0dd6c1.png)

but when I query the API, I get:
![image](https://user-images.githubusercontent.com/36129614/84045932-1f24ce00-a9b2-11ea-858f-5df511f1da4d.png)

When I tried to change the configuration (metricsQuery) to:

```
    - seriesQuery: 'http_requests_total'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'http_requests_total'
```
and queried the API, I get:
![image](https://user-images.githubusercontent.com/36129614/84046066-48455e80-a9b2-11ea-9ef7-ca485221b5f2.png)

which is the {status="4XX"} filter of http_requests_total:
![image](https://user-images.githubusercontent.com/36129614/84046155-627f3c80-a9b2-11ea-8055-fc20e5ef4379.png)

Is this normal?

Best Regards,
