### ISSUE TITLE
Metrics Discovery works but no values?

### ISSUE THREAD

**Issue by ntkjer** [DirectXMan12/k8s-prometheus-adapter#300]
Posted this blurb in a comment of another issue in the same vein, but wanted to post it here seperately for visibility as well. I'm currently not able to retrieve metrics from the defined adapter config. The service discovery for this target works at the root but no values are being populated.  

Adapter config looks like: 
``` 
   - seriesQuery: 'nginx_ingress_controller_nginx_process_requests_total{kubernetes_namespace!="",controller_pod!="",controller_namespace!=""}'
     resources:
       #template: "app_kubernetes_<<.Resource>>"
       overrides:
         kubernetes_namespace: {resource: "namespace"}
         #app_kubernetes_io_name: {resource: "app_kubernetes_io_name"}
         controller_namespace: {resource: "namespace"}
         controller_pod: {resource: "pod"}
    name:
      matches: "^(.*)_total"
      as: "${1}_per_second"
    metricsQuery: 'sum(rate(<<.Series>>{.LabelMatchers>>}[2m]))'
```
I can also list metrics that were discovered as so:
```
❯ k get --raw /apis/custom.metrics.k8s.io/v1beta1 | jq .
{
  "kind": "APIResourceList"
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "namespaces/nginx_ingress_controller_nginx_process_requests_per_second",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
          "get"
      ] 
    }
  ]
}
```
but alas, no metric as well when I query the specified target:
```
❯ k get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/ingress-nginx/pods/*/nginx_ingress_controller_nginx_process_requests_per_second" | jq .
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/ingress-nginx/pods/%2A/nginx_ingress_controller_nginx_process_requests_per_second"
  },
  "items": []
}
```

as far as how my Prometheus query looks like: `rate(nginx_ingress_controller_nginx_process_requests_total[2m])` 
```
{app_kubernetes_io_instance="ingress-nginx",app_kubernetes_io_managed_by="Helm",
app_kubernetes_io_name="ingress-nginx-metrics",app_kubernetes_io_version="0.32.0",controller_class="nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-786b647797-crkf5",
helm_sh_chart="ingress-nginx-2.0.3",instance="10.200.instance.ip:10254",job="kubernetes-service-endpoints",kubernetes_name="ingress-nginx-metrics",kubernetes_namespace="ingress-nginx",kubernetes_node="ip-blah.ec2.internal"}
 
```
