### ISSUE TITLE
HPA is forbidden to fetch external metrics

### ISSUE THREAD

**Issue by EugeneAikashev** [DirectXMan12/k8s-prometheus-adapter#303]
HI there,
My external metric is _as_queue_total_test_, k8s version is _v1.15.11-eks-af3caf, AWS EKS_
It looks good when I check by kubectl:
```
 kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/api/as_queue_total_test" | jq .
{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/api/as_queue_total_test"
  },
  "items": [
    {
      "metricName": "as_queue_total_test",
      "metricLabels": {},
      "timestamp": "2020-07-17T20:38:00Z",
      "value": "2016"
    }
  ]
}
```
But HPA can't get access to metric:
```
kubectl -n api describe hpa.v2beta2.autoscaling hpa-test
Name:                                            hpa-test
Namespace:                                       api
Labels:                                          <none>
Annotations:                                     <none>
CreationTimestamp:                               Fri, 17 Jul 2020 23:00:06 +0300
Reference:                                       Deployment/addons-worker
Metrics:                                         ( current / target )
  "as_queue_total_test" (target average value):  <unknown> / 10101
Min replicas:                                    2
Max replicas:                                    3
Deployment pods:                                 2 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric api/as_queue_total_test/nil: unable to fetch metrics from external metrics API: as_queue_total_test.external.metrics.k8s.io is forbidden: User "system:serviceaccount:kube-system:horizontal-pod-autoscaler" cannot list resource "as_queue_total_test" in API group "external.metrics.k8s.io" in the namespace "api"
Events:
  Type     Reason                        Age                   From                       Message
  ----     ------                        ----                  ----                       -------
  Warning  FailedComputeMetricsReplicas  46m (x12 over 49m)    horizontal-pod-autoscaler  Invalid metrics (1 invalid out of 1), last error was: failed to get as_queue_total_test external metric: unable to get external metric api/as_queue_total_test/nil: unable to fetch metrics from external metrics API: as_queue_total_test.external.metrics.k8s.io is forbidden: User "system:serviceaccount:kube-system:horizontal-pod-autoscaler" cannot list resource "as_queue_total_test" in API group "external.metrics.k8s.io" in the namespace "api"
  Warning  FailedGetExternalMetric       4m8s (x178 over 49m)  horizontal-pod-autoscaler  unable to get external metric api/as_queue_total_test/nil: unable to fetch metrics from external metrics API: as_queue_total_test.external.metrics.k8s.io is forbidden: User "system:serviceaccount:kube-system:horizontal-pod-autoscaler" cannot list resource "as_queue_total_test" in API group "external.metrics.k8s.io" in the namespace "api"
```
The HPA itself:
```
kubectl -n api get hpa.v2beta2.autoscaling hpa-test -o yaml --export
Flag --export has been deprecated, This flag is deprecated and will be removed in future.
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: hpa-test
  selfLink: /apis/autoscaling/v2beta2/namespaces/api/horizontalpodautoscalers/hpa-test
spec:
  maxReplicas: 3
  metrics:
  - external:
      metric:
        name: as_queue_total_test
      target:
        averageValue: "10101"
        type: AverageValue
    type: External
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: addons-worker
status:
  conditions: null
  currentMetrics: null
  currentReplicas: 0
  desiredReplicas: 0
```
Apiservices v1beta1.external.metrics.k8s.io
```
kubectl describe apiservices v1beta1.external.metrics.k8s.io
Name:         v1beta1.external.metrics.k8s.io
Namespace:    
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"apiregistration.k8s.io/v1beta1","kind":"APIService","metadata":{"annotations":{},"name":"v1beta1.external.metrics.k8s.io"},...
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2020-07-17T19:56:31Z
  Resource Version:    34919746
  Self Link:           /apis/apiregistration.k8s.io/v1/apiservices/v1beta1.external.metrics.k8s.io
  UID:                 3dff9a0c-962a-4539-ac70-a326f768a08f
Spec:
  Group:                     external.metrics.k8s.io
  Group Priority Minimum:    100
  Insecure Skip TLS Verify:  true
  Service:
    Name:            prometheus-adapter
    Namespace:       infra
    Port:            443
  Version:           v1beta1
  Version Priority:  100
Status:
  Conditions:
    Last Transition Time:  2020-07-17T19:57:02Z
    Message:               all checks passed
    Reason:                Passed
    Status:                True
    Type:                  Available
Events:                    <none>
```

Any ideas what I missed ?
