### ISSUE TITLE
Empty metrics in k8s metrics api

### ISSUE THREAD

**Issue by Nurza** [DirectXMan12/k8s-prometheus-adapter#321]
Hello, I am really struggling with getting kafka metrics with k8s-prometheus. Here is some informations:

K8 version: 1.18.9
Prometheus version: 2.20.1 (Installed with helm: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/Chart.yaml)
Adapter version: 0.7.0 (Installed with helm: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-adapter/Chart.yaml)

The content of ` /etc/adapter/config.yaml` (ask me if you need the entire Helm `value.yaml`)
```yaml
externalRules:
- metricsQuery: <<.Series>>{<<.LabelMatchers>>}
  resources:
    template: <<.Resource>>
  seriesQuery: '{__name__=~"^kafka_.*"}'
```

When I am using curl to get metrics from prometheus:

```shell
curl -s 'http://prometheus-server.prometheus.svc.cluster.local/api/v1/query' --data-urlencode 'query={__name__=~"^kafka_.*"}'|jq
```

```json
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "kafka_brokers",
          "instance": "kafka-exporter.kafka.svc.cluster.local:9308",
          "job": "kafka"
        },
        "value": [
          1601472922.625,
          "3"
        ]
      },
      {
        "metric": {
          "__name__": "kafka_consumergroup_current_offset",
          "consumergroup": "KafkaWebViewConsumer-UserId2-web-f44af2b94d9a2613e5def7ec17c2d2ea20420cb1",
          "instance": "kafka-exporter.kafka.svc.cluster.local:9308",
          "job": "kafka",
          "partition": "0",
          "topic": "worker.progress"
        },
        "value": [
          1601472922.625,
          "496"
        ]
      },
      {
        "metric": {
          "__name__": "kafka_consumergroup_current_offset",
          "consumergroup": "KafkaWebViewConsumer-UserId2-web-f44af2b94d9a2613e5def7ec17c2d2ea20420cb1",
          "instance": "kafka-exporter.kafka.svc.cluster.local:9308",
          "job": "kafka",
          "partition": "1",
          "topic": "worker.progress"
        },
        "value": [
          1601472922.625,
          "499"
        ]
      },
      {
        "metric": {
          "__name__": "kafka_consumergroup_current_offset",
          "consumergroup": "KafkaWebViewConsumer-UserId2-web-f44af2b94d9a2613e5def7ec17c2d2ea20420cb1",
          "instance": "kafka-exporter.kafka.svc.cluster.local:9308",
          "job": "kafka",
          "partition": "2",
          "topic": "worker.progress"
        },
        "value": [
          1601472922.625,
          "496"
        ]
      },

...

    ]
  }
}
```

But when I am querying k8s metrics api, I am getting empty items:

```shell
kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/*/kafka_consumergroup_lag" | jq
{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/%2A/kafka_consumergroup_lag"
  },
  "items": []
}
```

Do you know what am I doing wrong please? Thank you in advance for your time.

**Comment by Nurza** [comment]
I finally managed to fix this issue by putting this in the adapter's helm Chart value.yaml file:

```yaml
rules:
  default: false
  resource: {}
  external:
    - seriesQuery: 'kafka_consumergroup_lag'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "pod"}
      name:
       matches: "kafka_consumergroup_lag"
       as: "kafka_consumergroup_lag"
      metricsQuery: 'avg_over_time(kafka_consumergroup_lag{topic=~".*",consumergroup=~".*"}[1m])'
```
