### ISSUE TITLE
Image from dockerhub is crashing

### ISSUE THREAD

**Issue by flaker** [DirectXMan12/k8s-prometheus-adapter#329]
I didn't change my config at all, just pulled the new image (are there any specifics for updating?). Everything seems to start properly and then it crashes.

```
F1028 18:58:09.254329       1 openapi.go:39] Failed to build open api spec for root: non-body Restful parameter type should be a simple type, but got : v1.ResourceVersionMatch
```

I am not sure what's "latest" in dockerhub since the last tag I see here is 0.8.0.

directxman12/k8s-prometheus-adapter-amd64:latest
DIGEST:sha256:ba5a8b32ddbe254b468700afb5ec2187a7cd9475b15c6f067bb8e99014ff923e

**Comment by SockenSalat** [comment]
I tried to deploy v0.8.1 an ran into the same error

**Comment by kforsthoevel** [comment]
Same thing here with v0.8.1

**Comment by effndc** [comment]
The timing for this issue correlates with the commits from October 28th, I had several successful deployments prior to these commits and none since they were applied.

https://github.com/DirectXMan12/k8s-prometheus-adapter/commit/752ce847239b82078a9cdd6d80979bee443475d3#diff-4d0b81c92e53ab757dd6ce4dca5fdf332665e5e6d01e2e8465e517f5549886cd
https://github.com/DirectXMan12/k8s-prometheus-adapter/commit/752ce847239b82078a9cdd6d80979bee443475d3#diff-4d0b81c92e53ab757dd6ce4dca5fdf332665e5e6d01e2e8465e517f5549886cd

**Comment by cheng0214** [comment]
I test v0.7.0. It's ok.  maybe you can test it.

**Comment by johanneswuerbach** [comment]
Could you share the config you are using? We also updated to 0.8.0 and haven't see in a crash in ~4 days.

**Comment by s-urbaniak** [comment]
also could you also please submit the kubernetes versions? it _sounds_ like it is related.

**Comment by shreben** [comment]
I'm using k8s 1.17.13.

**Comment by effndc** [comment]
Kubernetes v1.18.4 here.

**Comment by cheng0214** [comment]
k8s version:  v1.18.8 (docker for Desktop Mac)
I also meet the cash issue with 0.8.0 and 0.8.1. Now use 0.7.0 is normal.
k8s-prometheus-adapter config is below:
```
  config.yaml: |
    rules:
    - seriesQuery: 'http_requests_total{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
```

**Comment by SockenSalat** [comment]
I'm using `v1.19.2` the confguration works fine with `v0.7.0` and `v0.8.0` but crashes with `v0.8.1`.

POD's log:

```
I1104 08:24:11.672988       1 adapter.go:98] successfully using in-cluster auth
F1104 08:24:12.414912       1 openapi.go:39] Failed to build open api spec for root: non-body Restful parameter type should be a simple type, but got : v1.ResourceVersionMatch
goroutine 1 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.stacks(0xc0000f6001, 0xc0006bc000, 0xb0, 0x1c6)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:996 +0xb8
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.(*loggingT).output(0x31aba20, 0xc000000003, 0x0, 0x0, 0xc0001a1730, 0x30e0621, 0xa, 0x27, 0x0)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:945 +0x19d
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.(*loggingT).printf(0x31aba20, 0x3, 0x0, 0x0, 0x1d5cd4d, 0x2a, 0xc000911d40, 0x1, 0x1)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.Fatalf(...)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:1463
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/routes.OpenAPI.Install(0xc00047e1b0, 0xc0008ce3f0, 0xc000174850, 0x1d41a60, 0x1a)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/routes/openapi.go:39 +0x104
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc00000a1e0, 0xc0003f8ae0)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:289 +0x2b0
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-sigs/custom-metrics-apiserver/pkg/cmd.(*AdapterBase).Run(0xc0006b8dc0, 0xc0000c80c0, 0xc000273a00, 0x0)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-sigs/custom-metrics-apiserver/pkg/cmd/builder.go:287 +0x63
main.main()
        /go/src/github.com/directxman12/k8s-prometheus-adapter/cmd/adapter/adapter.go:303 +0x764

goroutine 33 [chan receive]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x31aba20)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2.init.0
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/klog/v2/klog.go:416 +0xd6

goroutine 64 [select]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1df8f78, 0x2067f00, 0xc0003f8240, 0x1, 0xc0000c80c0)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x13f
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1df8f78, 0x12a05f200, 0x0, 0xc0004f4e01, 0xc0000c80c0)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xaa
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x1df8f78, 0x12a05f200)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
created by github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/component-base/logs.InitLogs
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a

goroutine 416 [chan receive]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc000735e60)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/client-go/util/workqueue/queue.go:198 +0xe0
created by github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/client-go/util/workqueue.newQueue
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/client-go/util/workqueue/queue.go:58 +0x132

goroutine 100 [syscall]:
os/signal.signal_recv(0x45f136)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 120 [IO wait]:
internal/poll.runtime_pollWait(0x7fa8833c7ea0, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00021a698, 0x72, 0x1e00, 0x1eb6, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00021a680, 0xc000576000, 0x1eb6, 0x1eb6, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc00021a680, 0xc000576000, 0x1eb6, 0x1eb6, 0x203000, 0x0, 0x1e72)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000f7d90, 0xc000576000, 0x1eb6, 0x1eb6, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x68
crypto/tls.(*atLeastReader).Read(0xc0008072c0, 0xc000576000, 0x1eb6, 0x1eb6, 0x1000, 0x400, 0xc00085b920)
        /usr/local/go/src/crypto/tls/conn.go:780 +0x60
bytes.(*Buffer).ReadFrom(0xc000163058, 0x2066540, 0xc0008072c0, 0x40a295, 0x1ac6be0, 0x1ca5b40)
        /usr/local/go/src/bytes/buffer.go:204 +0xb4
crypto/tls.(*Conn).readFromUntil(0xc000162e00, 0x2068c60, 0xc0000f7d90, 0x5, 0xc0000f7d90, 0x203000)
        /usr/local/go/src/crypto/tls/conn.go:802 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000162e00, 0x0, 0x0, 0xc000807280)
        /usr/local/go/src/crypto/tls/conn.go:609 +0x124
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0xc000162e00, 0xc000509000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1255 +0x161
bufio.(*Reader).Read(0xc0004cb320, 0xc0001a82d8, 0x9, 0x9, 0xc00085bcc0, 0x0, 0x9b3b25)
        /usr/local/go/src/bufio/bufio.go:226 +0x26a
io.ReadAtLeast(0x20663a0, 0xc0004cb320, 0xc0001a82d8, 0x9, 0x9, 0x9, 0xc0000ca050, 0x0, 0x2066740)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.readFrameHeader(0xc0001a82d8, 0x9, 0x9, 0x20663a0, 0xc0004cb320, 0x0, 0x0, 0xc0005a4c60, 0x0)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/frame.go:237 +0x87
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001a82a0, 0xc0005a4c60, 0x0, 0x0, 0x0)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/frame.go:492 +0xa1
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00085bfb8, 0x0, 0x0)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/transport.go:1794 +0xbe
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc0000a7e00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/transport.go:1716 +0xa3
created by github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*Transport).newClientConn
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/transport.go:695 +0x62f
...
```

**Comment by s-urbaniak** [comment]
ok, i am looking into this :thinking:

**Comment by s-urbaniak** [comment]
@SockenSalat do you mind to share your configuration?

**Comment by SockenSalat** [comment]
@s-urbaniak my config looks as follows:

```
    rules:
    - seriesQuery: 'epp_connections'
      resources:
        overrides:
          kubernetes_namespace: 
            resource: namespace
          kubernetes_pod_name:
            resource: pod
      name:
        matches: "epp_connections"
        as: "epp_sessions_per_minute"
      metricsQuery: 'rate(epp_connections[1m]) * 60'
      
    - seriesQuery: 'epp_connections'
      resources:
        overrides:
          kubernetes_namespace: 
            resource: namespace
          kubernetes_pod_name:
            resource: pod
      name:
        matches: "epp_connections"
      metricsQuery: 'epp_connections'
      
    - seriesQuery: 'epp_command_latency_count'
      resources:
        overrides:
          kubernetes_namespace: 
            resource: namespace
          kubernetes_pod_name:
            resource: pod
      name:
        matches: "epp_command_latency_count"
        as: "epp_commands_per_minute"
      metricsQuery: 'sum(rate(epp_command_latency_count[1m]) * 60) by (kubernetes_pod_name, kubernetes_namespace)'
      
    - seriesQuery: 'rdds_whois_active_threads'
      metricsQuery: 'rate(rdds_whois_active_threads[1m]) * 60'
      name:
        matches: "rdds_whois_active_threads"
        as: "whois_threads_active"
      resources:
          overrides:
            kubernetes_namespace: 
              resource: namespace
            kubernetes_pod_name:
              resource: pod
              
    - seriesQuery: 'rdds_whois_query_latency_count'
      metricsQuery: 'sum(rate(rdds_whois_query_latency_count[1m])) by (kubernetes_pod_name)  / sum(rdds_whois_max_threads) by (kubernetes_pod_name)'
      name:
        matches: 'rdds_whois_query_latency_count'
        as: 'whois_qps_per_thread'
      resources:
          overrides:
            kubernetes_namespace: 
              resource: namespace
            kubernetes_pod_name:
              resource: pod
              
    - seriesQuery: 'rdds_whois_threads'
      metricsQuery: 'sum(rdds_whois_threads) by (kubernetes_pod_name, kubernetes_namespace) / count(rdds_whois_threads) by (kubernetes_pod_name, kubernetes_namespace)'
      resources:
          overrides:
            kubernetes_namespace: 
              resource: namespace
            kubernetes_pod_name:
              resource: pod
       
```

**Comment by s-urbaniak** [comment]
ok, thank you @SockenSalat I think we have a bug in custom metrics handling.

**Comment by dgrisonnet** [comment]
I was able to reproduce this bug in a `v1.19.2` cluster with the adapter `v0.8.1` only. The bug shows up only with custom and external metrics.
I used the following configurations:
```
rules:
- seriesQuery: 'http_requests_total{kubernetes_namespace!="",kubernetes_pod_name!=""}'
  resources:
    overrides:
      kubernetes_namespace: {resource: "namespace"}
      kubernetes_pod_name: {resource: "pod"}
  name:
    matches: "^(.*)_total"
    as: "${1}_per_second"
  metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
```
```
externalRules:
  - seriesQuery: '{__name__=~"^.*_queue_(length|size)$",namespace!=""}'
  resources:
    overrides:
      namespace:
        resource: namespace
  name:
    matches: ^.*_queue_(length|size)$
    as: "$0"
  metricsQuery: max(<<.Series>>{<<.LabelMatchers>>})
```

As the bug doesn't seem to occur in `v0.8.0`, I'd guess that it was introduced by the k8s dependencies update to 1.19.
Also, this bug seems to be a bug in `custom-metrics-apiserver` more than this repository as I was also able to reproduce this error with the `test-adapter` of this repo.

@johanneswuerbach does it ring at bell to you?
