### ISSUE TITLE
Question: I don't understand how to write a rule. Help me write correct seriesQuery with template.

### ISSUE THREAD

**Issue by MatthewPattell** [DirectXMan12/k8s-prometheus-adapter#333]
I have prometheus data:
```
nginx_ingress_controller_requests{ingress=~"^microservices-ingress-.*",service!="",status="200"}
```

Results:
```
nginx_ingress_controller_requests{controller_class="nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-66477d445d-7zs7s",exported_namespace="ingress-nginx",ingress="microservices-ingress-hello1",instance="10.244.1.53:10254",job="kubernetes-pods",namespace="ingress-nginx",pod="ingress-nginx-controller-66477d445d-7zs7s",service="my-service1",status="200"}

nginx_ingress_controller_requests{controller_class="nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-66477d445d-7zs7s",exported_namespace="ingress-nginx",ingress="microservices-ingress-hello2",instance="10.244.1.53:10254",job="kubernetes-pods",namespace="ingress-nginx",pod="ingress-nginx-controller-66477d445d-7zs7s",service="my-service2",status="200"}
```

My adapter config:
```
    - seriesQuery: 'nginx_ingress_controller_requests{ingress=~"^microservices-ingress-.*",service!="",status="200"}'
      resources:
        overrides:
          service:
            resource: deployment
            group: apps
      name:
        as: request_per_second
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)
```

The namespace name is contained in "ingress" key. Example: **microservices-ingress-hello2**, where **hello2** is namespace.
I don't understand how to write a rule.

I want use **request_per_second** in hpa like:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-service2-hpa
  namespace: hello2
.....
    - type: Object
      object:
        metric:
          name: request_per_second
        describedObject:
          apiVersion: apps/v1
          kind: Deployment
          name: my-service2
        target:
          type: Value
          value: 5
```
