### ISSUE TITLE
Division in metricsQuery while supplying ConfigMap

### ISSUE THREAD

**Issue by pulkitsapra** [DirectXMan12/k8s-prometheus-adapter#345]
Hi!

I want to do metric Division in "metricsQuery" parameter while suppying my custom Config Map. Is it possible to do it?
```
rules:
  default: false
  custom:
  - seriesQuery: '{namespace!="",__name__!~"^container_.*"}'
    resources:
      overrides:
          namespace:
            resource: namespace
    name:
      matches:  "^(.*)_workers$"
      as: "foo_k"
    metricsQuery: 'redis_queue_length_workers / celery_workers'
  resource: {}
```

P.S I can get individual value for both the metrics 'redis_queue_length_worker' and 'celery_workers' by changing the metricsQuery as follows : 
` metricsQuery: redis_queue_length_workers` or ` metricsQuery: celery_workers` but when I try to do division I get error when i try to hit the API
` kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/default/metrics/foo_k | jq .`

 Error :
> Error from server (InternalError): Internal error occurred: unable to fetch metrics

This issue is same as #251 . Raising this again as there is no update on that issue.

**Comment by pulkitsapra** [comment]
Just figured out a solution to it!

For the application of an operator like ( '+', '-', '/', '*') to 2 series, **the labels must match exactly** otherwise, the output is 'No data found'. If the labels are not the same, one can specify the keyword **' ignoring '** and put the labels that don't match in braces. Pl see the config file below that worked for me.

```
rules:
  default: false
  custom:
  - seriesQuery: 'redis_queue_length'
    resources:
      overrides:
          namespace:
            resource: namespace
    name:
      matches:  "redis_queue_length"
      as: "foo"
    metricsQuery: redis_queue_length{instance="redis-exporter:9000",job="pr_metrics_exporter",namespace="default"}  /  ignoring(instance) celery_workers{instance="celery-exporter:9540",job="pr_metrics_exporter",namespace="default"} 
  resource: {}
```
