### ISSUE TITLE
Cluster role needs some more previleges and missing luxas/autoscale-demo image, while following Walkthrough

### ISSUE THREAD

**Issue by adityap101** [DirectXMan12/k8s-prometheus-adapter#73]
1. I followed walkthrough to deploy sample app. I could get prometheus and prometheus-adapter pods up and running. When i check logs of prometheus container it shows:
`level=error ts=2018-05-28T05:47:05.224231355Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:296: Failed to watch *v1.Pod: unknown (get pods)"`

    It works when i updated resource-lister.yaml to use `verbs: '*'` instead of `'list'`, as shown below:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-lister
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
  ```
2. When i tried **Collecting Application Metrics** steps, i was unable to find `luxas/autoscale-demo` image on dockerhub. 
How do I get this image or build it to move ahead with the walkthrough?
