### ISSUE TITLE
rules do not seem to work

### ISSUE THREAD

**Issue by white-hat** [DirectXMan12/k8s-prometheus-adapter#96]
For some reason my rules are ignored,
for example, I got a `nginx_connections_current` metric 
```bash
> kubectl get --raw '/apis/custom.metrics.k8s.io/v1beta1/namespaces/satellite/pods/web-backend-5dbc7475ff-54tfv/nginx_connections_current' | jq .
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/satellite/pods/web-backend-5dbc7475ff-54tfv/nginx_connections_current"
  },
  "items": [
    {
      "describedObject": {
        "kind": "Pod",
        "name": "web-backend-5dbc7475ff-54tfv",
        "apiVersion": "/__internal"
      },
      "metricName": "nginx_connections_current",
      "timestamp": "2018-08-09T01:30:34Z",
      "value": "2"
    }
  ]
}
```
Now I create a rule
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
    - seriesQuery: 'nginx_connections_current{state="active"}'
      name:
        as: "ilya"
      metricsQuery: 'sum(nginx_connections_current{state="active"})'
```
And I expect a new metric `ilya` to be available via API.
After applying the config map and recreating the pod
```bash
$ kubectl apply -f custom-metrics-config-map.yaml
$ kubectl -n monitoring delete pod custom-metrics-apiserver-7f4996f669-vbvql   
```
I still do not see any changes
```bash
$ kubectl get --raw '/apis/custom.metrics.k8s.io/v1beta1/namespaces/satellite/pods/web-backend-5dbc7475ff-54tfv/ilya' | jq .
Error from server (NotFound): the server could not find the metric ilya for pods
```
Am I missing something? please help

**Comment by DirectXMan12** [comment]
You don't have any resources associated with the metric, so it won't show up.  You need a `resources` section to indicate which resources the metric is associated with.  See [the config docs](/docs/config.md) or the config walkthrough in #95 for more information.

**Comment by white-hat** [comment]
@DirectXMan12  thank you for a prompt response!
after reading `config.md` everything makes sense, I managed to get my custom metrics for the pod
```yaml
    - seriesQuery: 'nginx_connections_current{state="active"}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
          service:
            resource: service
      name:
        as: "ilya"
      metricsQuery: 'sum(<<.Series>>{state="active",<<.LabelMatchers>>}) by (<<.GroupBy>>)'
```
```shell
kubectl get --raw '/apis/custom.metrics.k8s.io/v1beta1/namespaces/satellite/pods/web-backend-5dbc7475ff-54tfv/ilya' | jq .
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/satellite/pods/web-backend-5dbc7475ff-54tfv/ilya"
  },
  "items": [
    {
      "describedObject": {
        "kind": "Pod",
        "name": "web-backend-5dbc7475ff-54tfv",
        "apiVersion": "/__internal"
      },
      "metricName": "ilya",
      "timestamp": "2018-08-09T19:48:56Z",
      "value": "1"
    }
  ]
}
```
